import { useEffect, useState } from 'react'
import { Building2, MapPin, Phone, Ruler, Pencil, Save, Trash2 } from 'lucide-react'
import { api } from '../services/api'
import { useAuth } from '../contexts/AuthContext'
import PageHeader from '../components/PageHeader'
import Loading from '../components/Loading'
import Toast from '../components/Toast'
import DeleteConfirmationModal from '../components/DeleteConfirmationModal'
import { getApiErrorMessage } from '../utils/apiError'

const empty={name:'',address:'',city:'Dhaka',contact_phone:'',total_area:'',notes:''}
export default function BuildingPage(){const{user}=useAuth();const[building,setBuilding]=useState(null);const[form,setForm]=useState(empty);const[edit,setEdit]=useState(false);const[loading,setLoading]=useState(true);const[deleteOpen,setDeleteOpen]=useState(false);const[deleting,setDeleting]=useState(false);const[toast,setToast]=useState(null);const canWrite=['administrator','building_manager'].includes(user?.role)
async function load(){setLoading(true);try{const rows=await api.get('/buildings');const b=rows[0]||null;setBuilding(b);setForm(b||empty)}catch(e){setToast({type:'error',message:getApiErrorMessage(e)})}finally{setLoading(false)}} useEffect(()=>{load()},[])
async function save(e){e.preventDefault();try{const payload={...form,total_area:Number(form.total_area||0),contact_phone:form.contact_phone||null,notes:form.notes||null};const b=building?await api.patch(`/buildings/${building.id}`,payload):await api.post('/buildings',payload);setBuilding(b);setEdit(false);setToast({message:'Building profile saved.'})}catch(e2){setToast({type:'error',message:getApiErrorMessage(e2)})}}
async function removeBuilding(){if(!building||deleting)return;setDeleting(true);try{await api.delete(`/buildings/${building.id}`);setBuilding(null);setForm(empty);setDeleteOpen(false);setToast({message:'Building deleted successfully.'});await load()}catch(e){setToast({type:'error',message:getApiErrorMessage(e)})}finally{setDeleting(false)}}
if(loading)return <><PageHeader title="Building Profile"/><Loading/></>
return <><PageHeader title="Building Profile" subtitle="The single-building master record for BRMS Version 1." actions={canWrite&&!edit?<div className="flex gap-2">{building&&<button className="btn-secondary text-rose-600 hover:border-rose-200 hover:bg-rose-50" onClick={()=>setDeleteOpen(true)} title="Delete building" aria-label="Delete building"><Trash2 size={16}/>Delete</button>}<button className="btn-primary" onClick={()=>setEdit(true)}><Pencil size={16}/>Edit profile</button></div>:null}/>
<div className="grid gap-5 xl:grid-cols-[1fr_.42fr]"><div className="card overflow-hidden"><div className="relative h-52 bg-slate-950 p-7 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(56,189,248,.28),transparent_30%),radial-gradient(circle_at_15%_90%,rgba(34,211,238,.14),transparent_32%)]"/><div className="relative flex h-full flex-col justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-sky-300"><Building2/></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-sky-300">Primary Asset</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight">{building?.name||'No building configured'}</h2><p className="mt-1 flex items-center gap-2 text-sm text-slate-400"><MapPin size={15}/>{building?.address||'Create the building profile to begin.'}</p></div></div></div>
{edit||!building?<form className="grid grid-cols-1 gap-4 p-6 sm:grid-cols-2" onSubmit={save}><Field label="Building name" name="name" form={form} setForm={setForm}/><Field label="City" name="city" form={form} setForm={setForm}/><div className="sm:col-span-2"><Field label="Address" name="address" form={form} setForm={setForm}/></div><Field label="Contact phone" name="contact_phone" form={form} setForm={setForm} optional/><Field label="Total area (sq ft)" name="total_area" type="number" form={form} setForm={setForm} optional/><div className="sm:col-span-2"><label className="label">Notes</label><textarea className="field min-h-28" value={form.notes||''} onChange={e=>setForm({...form,notes:e.target.value})}/></div><div className="sm:col-span-2 flex justify-end gap-2">{building&&<button type="button" className="btn-secondary" onClick={()=>{setEdit(false);setForm(building)}}>Cancel</button>}<button className="btn-primary"><Save size={16}/>Save profile</button></div></form>:<div className="grid gap-0 sm:grid-cols-2"><Info icon={MapPin} label="Location" value={`${building.address}, ${building.city}`}/><Info icon={Phone} label="Contact" value={building.contact_phone||'Not provided'}/><Info icon={Ruler} label="Total area" value={building.total_area?`${Number(building.total_area).toLocaleString()} sq ft`:'Not provided'}/><Info icon={Building2} label="System scope" value="Single commercial building"/></div>}</div>
<div className="space-y-5"><div className="card p-5"><p className="panel-title">Version 1 scope</p><p className="mt-2 text-sm leading-6 text-slate-500">BRMS is intentionally configured around one commercial building with multiple floors and shops, preserving a clean foundation for future expansion.</p></div><div className="card p-5"><p className="panel-title">Data governance</p><div className="mt-4 space-y-3 text-sm text-slate-600"><p>• Building → Floor → Shop hierarchy is validated by the API.</p><p>• Historical financial records are protected from unsafe deletion.</p><p>• Role permissions are enforced server-side.</p></div></div></div></div><DeleteConfirmationModal open={deleteOpen} title="Delete Building?" description="The building can only be deleted after all related floors have been removed." recordName={building?.name} confirmLabel="Delete Building" loading={deleting} onConfirm={removeBuilding} onCancel={()=>setDeleteOpen(false)}/><Toast toast={toast} onClose={()=>setToast(null)}/></>}
function Field({label,name,form,setForm,type='text',optional}){return <div><label className="label">{label}{!optional&&' *'}</label><input className="field" type={type} required={!optional} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/></div>}
function Info({icon:Icon,label,value}){return <div className="border-t border-slate-100 p-6 sm:odd:border-r"><div className="flex items-center gap-2 text-slate-400"><Icon size={16}/><span className="text-xs font-bold uppercase tracking-wide">{label}</span></div><p className="mt-3 text-sm font-semibold leading-6 text-slate-800">{value}</p></div>}
