import { useEffect, useState } from 'react'
import { Layers3, Store, UsersRound, WalletCards, Zap, Wrench, ArrowUpRight, Building2 } from 'lucide-react'
import { api } from '../services/api'
import PageHeader from '../components/PageHeader'
import KpiCard from '../components/KpiCard'
import Loading from '../components/Loading'
import StatusBadge from '../components/StatusBadge'
import { money, monthLabel, titleCase } from '../utils/format'

export default function DashboardPage(){
  const [data,setData]=useState(null); const [error,setError]=useState('')
  useEffect(()=>{api.get('/dashboard').then(setData).catch(e=>setError(e.message))},[])
  if(!data) return <><PageHeader title="Executive Dashboard" subtitle="Real-time rental operations at a glance."/>{error?<p className="text-rose-600">{error}</p>:<Loading/>}</>
  const m=data.metrics; const occupancy=m.shops?Math.round(m.occupied_shops/m.shops*100):0; const collection=m.rent_expected?Math.round(m.rent_collected/m.rent_expected*100):0
  return <>
    <PageHeader eyebrow={`Overview • ${monthLabel(data.month)}`} title="Executive Dashboard" subtitle="A focused management view of occupancy, monthly collections, utilities and operational activity." actions={<button className="btn-secondary" onClick={()=>window.location.reload()}>Refresh overview</button>}/>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard icon={Layers3} label="Floors" value={m.floors} detail="Configured building levels"/><KpiCard icon={Store} label="Occupied shops" value={`${m.occupied_shops}/${m.shops}`} detail={`${occupancy}% portfolio occupancy`} tone="violet"/><KpiCard icon={UsersRound} label="Active tenants" value={m.active_tenants} detail={`${m.available_shops} shops currently available`} tone="emerald"/><KpiCard icon={WalletCards} label="Rent collected" value={money(m.rent_collected)} detail={`${collection}% of ${money(m.rent_expected)} expected`} tone="amber"/></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <div className="card p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="panel-title">Collection performance</p><p className="mt-1 text-sm text-slate-500">Monthly rent collection against expected active tenancy value.</p></div><ArrowUpRight className="text-slate-300"/></div><div className="mt-8 grid gap-6 md:grid-cols-[180px_1fr]"><div className="flex items-center justify-center"><div className="relative h-40 w-40 rounded-full" style={{background:`conic-gradient(#0ea5e9 ${collection}%, #e2e8f0 0)`}}><div className="absolute inset-4 flex flex-col items-center justify-center rounded-full bg-white"><span className="text-3xl font-extrabold">{collection}%</span><span className="text-xs font-semibold text-slate-400">Collected</span></div></div></div><div className="grid gap-3 sm:grid-cols-2"><Mini label="Expected rent" value={money(m.rent_expected)} icon={WalletCards}/><Mini label="Collected" value={money(m.rent_collected)} icon={ArrowUpRight}/><Mini label="Outstanding utilities" value={money(m.utility_due)} icon={Zap}/><Mini label="Maintenance spend" value={money(m.maintenance_cost)} icon={Wrench}/></div></div></div>
      <div className="card p-5 sm:p-6"><p className="panel-title">Occupancy health</p><p className="mt-1 text-sm text-slate-500">Availability across the configured commercial units.</p><div className="mt-6 overflow-hidden rounded-2xl bg-slate-100"><div className="h-3 rounded-2xl bg-gradient-to-r from-sky-500 to-cyan-400" style={{width:`${occupancy}%`}}/></div><div className="mt-6 grid grid-cols-2 gap-3"><Metric label="Occupied" value={m.occupied_shops}/><Metric label="Available" value={m.available_shops}/><Metric label="Total units" value={m.shops}/><Metric label="Occupancy" value={`${occupancy}%`}/></div><div className="mt-5 rounded-2xl bg-slate-950 p-4 text-white"><div className="flex items-center gap-3"><div className="rounded-xl bg-sky-400/15 p-2 text-sky-300"><Building2 size={18}/></div><div><p className="text-sm font-bold">Portfolio pulse</p><p className="mt-0.5 text-xs text-slate-400">{m.available_shops ? `${m.available_shops} unit(s) are ready for new assignments.`:'All active units are currently occupied.'}</p></div></div></div></div>
    </div>
    <div className="mt-5 card p-5 sm:p-6"><div className="mb-4 flex items-center justify-between"><div><p className="panel-title">Recent activity</p><p className="mt-1 text-sm text-slate-500">Latest recorded financial and operational actions.</p></div></div><div className="divide-y divide-slate-100">{data.recent_activity.map((r,i)=><div key={r.id+i} className="flex items-center gap-4 py-3.5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-500">{r.type==='Rent payment'?<WalletCards size={18}/>:r.type==='Utility bill'?<Zap size={18}/>:<Wrench size={18}/>}</div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-800">{r.type}</p><p className="text-xs text-slate-400">Record {String(r.id).slice(0,8).toUpperCase()}</p></div>{r.amount!=null&&<p className="text-sm font-bold text-slate-700">{money(r.amount)}</p>}<StatusBadge value={r.status}/></div>)}</div></div>
  </>
}
function Mini({label,value,icon:Icon}){return <div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center gap-2 text-slate-400"><Icon size={15}/><span className="text-[11px] font-bold uppercase tracking-wide">{label}</span></div><p className="mt-3 text-lg font-extrabold text-slate-900">{value}</p></div>}
function Metric({label,value}){return <div className="rounded-2xl border border-slate-100 p-4"><p className="text-2xl font-extrabold text-slate-900">{value}</p><p className="mt-1 text-xs font-semibold text-slate-400">{label}</p></div>}
