import { useEffect, useState } from 'react'
import { Printer, Download, WalletCards, Zap, Wrench, AlertCircle } from 'lucide-react'
import { api } from '../services/api'
import PageHeader from '../components/PageHeader'
import KpiCard from '../components/KpiCard'
import Loading from '../components/Loading'
import StatusBadge from '../components/StatusBadge'
import { money, monthLabel } from '../utils/format'

export default function ReportsPage(){const now=new Date();const defaultMonth=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;const[month,setMonth]=useState(defaultMonth);const[data,setData]=useState(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('')
async function load(){setLoading(true);setError('');try{setData(await api.get(`/reports/monthly?month=${month}`))}catch(e){setError(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[])
function csv(){if(!data)return;const lines=[['BRMS Monthly Report',month],[],['Metric','Amount'],...Object.entries(data.summary).map(([k,v])=>[k,v]),[],['Rent Records'],['Tenant','Shop','Status','Amount'],...data.rent_rows.map(r=>[r.tenant_name||'',r.shop_number||'',r.status,r.amount])];const blob=new Blob([lines.map(r=>r.map(c=>`"${String(c??'').replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`BRMS_Report_${month}.csv`;a.click();URL.revokeObjectURL(a.href)}
return <><PageHeader title="Monthly Reports" subtitle="Generate a concise operational and financial view for faculty review or management decisions." actions={<><button className="btn-secondary no-print" onClick={()=>window.print()}><Printer size={16}/>Print</button><button className="btn-primary no-print" onClick={csv} disabled={!data}><Download size={16}/>Export CSV</button></>}/><div className="no-print mb-5 card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><div><label className="label">Accounting month</label><input className="field" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></div><button className="btn-primary" onClick={load}>Generate report</button></div></div>{loading?<Loading label="Compiling monthly report…"/>:error?<p className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>:data&&<><div className="mb-5"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-sky-600">Official summary</p><h2 className="mt-1 text-xl font-extrabold">{monthLabel(data.month)}</h2></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard icon={WalletCards} label="Rent collected" value={money(data.summary.rent_collected)} detail={`${money(data.summary.rent_outstanding)} outstanding`} tone="emerald"/><KpiCard icon={AlertCircle} label="Expected rent" value={money(data.summary.rent_expected)} detail="Based on active assignments" tone="sky"/><KpiCard icon={Zap} label="Utilities" value={money(data.summary.utility_total)} detail={`${money(data.summary.utility_outstanding)} outstanding`} tone="amber"/><KpiCard icon={Wrench} label="Maintenance" value={money(data.summary.maintenance_total)} detail="Recorded monthly cost" tone="violet"/></div><ReportTable title="Rent collection detail" cols={['Tenant / Business','Shop','Status','Amount']} rows={data.rent_rows.map(r=>[r.tenant_name||'—',r.shop_number?`Shop ${r.shop_number}`:'—',<StatusBadge value={r.status}/>,money(r.amount)])}/><ReportTable title="Utility billing detail" cols={['Type','Month','Status','Amount']} rows={data.utility_rows.map(r=>[r.utility_type,r.accounting_month,<StatusBadge value={r.status}/>,money(r.amount)])}/><ReportTable title="Maintenance detail" cols={['Date','Description','Status','Cost']} rows={data.maintenance_rows.map(r=>[r.maintenance_date,r.description,<StatusBadge value={r.status}/>,money(r.cost)])}/></>}</>}
function ReportTable({title,cols,rows}){return <div className="mt-5 card p-5"><h3 className="panel-title mb-4">{title}</h3><div className="table-wrap"><table className="data-table"><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>):<tr><td colSpan={cols.length} className="text-center text-slate-400">No records for this month.</td></tr>}</tbody></table></div></div>}
